services:
  app:
    build: .
    env_file:
      - ./.env
    volumes:
      - ./.:/var/www/html

  db:
      image: mariadb
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: toor
          MYSQL_DATABASE: d2
          MYSQL_USER: d2
          MYSQL_PASSWORD: d2
      ports:
          - 7001:3306
